add rpm-ostree mode

diff --git a/files/system/usr/libexec/secureblue/upgrade-on-boot b/files/system/usr/libexec/secureblue/upgrade-on-boot
--- a/files/system/usr/libexec/secureblue/upgrade-on-boot
+++ b/files/system/usr/libexec/secureblue/upgrade-on-boot
@@ -2,56 +2,84 @@
 LOGFILE=/var/log/bootc-upgrade.log
 exec > >(tee -a "$LOGFILE") 2>&1
 
-echo "Starting bootc upgrade"
+echo "Starting upgrade-on-boot service"
 
-if bootc upgrade --check 2>&1 | grep -q "No changes"; then
-    echo "No update available, booting normally"
-    exit 0
+rpm_ostree_status=$(rpm-ostree status --json --booted)
+image_date=$(jq -cr '.deployments[0].timestamp' <<<"$rpm_ostree_status")
+current_seconds=$(date +%s)
+difference=$((current_seconds - image_date))
+# week=$((7 * 24 * 60 * 60))
+day=$((24 * 60 * 60))
+if (( difference < day )); then
+    echo "Image is less than a day old. Booting current deployment."
+    exit 0  
 fi
 
-echo "Update available, proceeding"
-
-BOOTC_OUTPUT=$(mktemp -u /run/bootc-upgrade-XXXXXX)
-mkfifo "$BOOTC_OUTPUT"
+UPDATE_FAILURE_STRING="Update failed, booting existing deployment..."
+CANCEL_STRING="Press Q to cancel and boot existing deployment"
 
 plymouth watch-keystroke --keys="q" --command "systemctl stop upgrade-on-boot.service" &
-plymouth change-mode --updates
-plymouth system-update --progress=0
-plymouth message --text="Press Q to cancel and boot existing deployment"
-echo "Plymouth initialized"
+plymouth message --text="$CANCEL_STRING"
+BOOTC_UPGRADE_CHECK_OUTPUT="$(bootc upgrade --check 2>&1)"
 
-while IFS= read -r line; do
-    echo "Got line: $line"
-    type=$(echo "$line" | jq -r '.type // empty')
-    echo "Type: $type"
-    case "$type" in
-        ProgressBytes)
-            bytes=$(echo "$line" | jq -r '.bytes')
-            bytes_total=$(echo "$line" | jq -r '.bytesTotal')
-            percent=$(echo "$bytes $bytes_total" | awk '{printf "%d", $1 / $2 * 100}')
-            echo "Percent: $percent"
-            if [ "$percent" -ge 100 ]; then
-                plymouth change-mode --boot-up
-                plymouth message --text="Deploying update... Press Q to cancel and boot existing deployment"
-            else
-                plymouth system-update --progress="$percent"
-            fi
-            ;;
-        ProgressSteps)
-            echo "ProgressSteps received"
-            ;;
-    esac
-done < "$BOOTC_OUTPUT" &
+if grep -q "local rpm-ostree modifications" <<< "$BOOTC_UPGRADE_CHECK_OUTPUT"; then
+    echo "Using rpm-ostree"
+    plymouth message --text="Staging update... $CANCEL_STRING"
+    rpm-ostree upgrade
+    RPM_OSTREE_EXIT=$?
+    if [ $RPM_OSTREE_EXIT -ne 0 ]; then
+        echo "$UPDATE_FAILURE_STRING"
+        plymouth message --text="$UPDATE_FAILURE_STRING"
+        exit 1
+    fi
+else
+    echo "Using bootc"
+    if grep -q "No changes" <<< "$BOOTC_UPGRADE_CHECK_OUTPUT"; then
+        echo "No update available, booting current deployment"
+        exit 0
+    fi
 
-bootc upgrade --quiet --progress-fd 3 3>"$BOOTC_OUTPUT"
-BOOTC_EXIT=$?
-echo "bootc exited with: $BOOTC_EXIT"
-rm -f "$BOOTC_OUTPUT"
+    echo "Update available, proceeding"
+    plymouth change-mode --updates
+    plymouth system-update --progress=0
+    echo "Plymouth initialized"
 
-if [ $BOOTC_EXIT -ne 0 ]; then
-    echo "Upgrade failed, booting existing deployment"
-    plymouth message --text="Update failed. Booting existing deployment..."
-    exit 0
+    BOOTC_OUTPUT=$(mktemp -u /run/bootc-upgrade-XXXXXX)
+    mkfifo "$BOOTC_OUTPUT"
+
+    while IFS= read -r line; do
+        echo "Got line: $line"
+        type=$(echo "$line" | jq -r '.type // empty')
+        echo "Type: $type"
+        case "$type" in
+            ProgressBytes)
+                bytes=$(echo "$line" | jq -r '.bytes')
+                bytes_total=$(echo "$line" | jq -r '.bytesTotal')
+                percent=$(echo "$bytes $bytes_total" | awk '{printf "%d", $1 / $2 * 100}')
+                echo "Percent: $percent"
+                if [ "$percent" -ge 100 ]; then
+                    plymouth change-mode --boot-up
+                    plymouth message --text="Deploying update... $CANCEL_STRING"
+                else
+                    plymouth system-update --progress="$percent"
+                fi
+                ;;
+            ProgressSteps)
+                echo "ProgressSteps received"
+                ;;
+        esac
+    done < "$BOOTC_OUTPUT" &
+
+    bootc upgrade --quiet --progress-fd 3 3>"$BOOTC_OUTPUT"
+    BOOTC_EXIT=$?
+    echo "bootc exited with: $BOOTC_EXIT"
+    rm -f "$BOOTC_OUTPUT"
+
+    if [ $BOOTC_EXIT -ne 0 ]; then
+        echo "$UPDATE_FAILURE_STRING"
+        plymouth message --text="$UPDATE_FAILURE_STRING"
+        exit 1
+    fi
 fi
 
 if bootc status --json | jq -e '.status.staged != null' > /dev/null 2>&1; then
